# General  
train_2d: False
no_eval: False
finetune: False
partial_train: null

# Traning 
epochs: 120
checkpoint_frequency: 30
batch_size: 2048  # 32
dropout: 0.0
learning_rate: 0.0005
weight_decay: 0.01
lr_decay: 0.99

# Model
maxlen: 9
dim_feat: 128  # 256
mlp_ratio: 4
depth: 5
dim_rep: 256  # 512
num_heads: 8
att_fuse: True
res_scale_init_values: [null, null, null, null, null] #[1.0, 1.0, 1.0, 1.0, 1.0]
layer_scale_init_values: [null, null, null, null, null]
st_mode1: "stage_s"
st_mode2: "stage_t"

# Data
data_root: data/motion3d/MB3D_f9s3/
subset_list: [H36M-SH]
dt_file: h36m_sh_conf_cam_source_final.pkl
clip_len: 9
data_stride: 3
rootrel: True
sample_stride: 1
num_joints: 17
no_conf: False
gt_2d: False

# Loss
lambda_3d_velocity: 20.0
lambda_scale: 0.5
lambda_lv: 0.0
lambda_lg: 0.0
lambda_a: 0.0
lambda_av: 0.0

# Augmentation
synthetic: False
flip: True
mask_ratio: 0.
mask_T_ratio: 0.
noise: False

